name: End-to-end tests
on: push
jobs:
  Regression_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests

      - name: Execute all test cases on Electron browser
        uses: cypress-io/github-action@v6
      
      - name: Execute all test cases on Chrome browser
        uses: cypress-io/github-action@v6
        with:
          browser: chrome

      - name: Execute all test cases On Edge browser
        uses: cypress-io/github-action@v6
        with:
          browser: edge