name: Cross Browser Parallel Test Execution
on: push
jobs:
  Electron_Regression_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Execute all test cases on Electron browser
        uses: cypress-io/github-action@v6

      - name: Electron browser test result
        if: always()
        run: |
          echo "This is the test result on Electron browser" >> $GITHUB_STEP_SUMMARY

      - name: Generate Electron test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Electron test Report
          path: cypress/reports/html

  Chrome_Regression_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Execute all test cases on Chrome browser
        uses: cypress-io/github-action@v6
        with:
          browser: chrome

      - name: Chrome browser test result
        if: always()
        run: |
            echo "This is the test result on Chrome browser" >> $GITHUB_STEP_SUMMARY

      - name: Generate Chrome test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Chrome test Report
          path: cypress/reports/html

  Edge_Regression_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Execute all test cases On Edge browser
        uses: cypress-io/github-action@v6
        with:
          browser: edge

      - name: Edge browser test result
        if: always()
        run: |
            echo "This is the test result on Edge browser" >> $GITHUB_STEP_SUMMARY

      - name: Generate Edge test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Edge test Report
          path: cypress/reports/html

  Firefox_Regression_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Execute all test cases On Firefox browser
        uses: cypress-io/github-action@v6
        with:
            browser: firefox

      - name: Firefox browser test result
        if: always()
        run: |
              echo "This is the test result on Firefox browser" >> $GITHUB_STEP_SUMMARY

      - name: Generate Firefox test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Firefox test Report
          path: cypress/reports/html

      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          #SLACK_CHANNEL: general
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Test Automation Report: https://github.com/Lord-Delis/Automata/actions/runs/${{github.run_id}}'
          SLACK_TITLE: Cypress Web Test
          #SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}